
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_GPIO_CONTROL_AXI_GPIO_AFE_CONTROL_DEVICE_ID,
		XPAR_GPIO_CONTROL_AXI_GPIO_AFE_CONTROL_BASEADDR,
		XPAR_GPIO_CONTROL_AXI_GPIO_AFE_CONTROL_INTERRUPT_PRESENT,
		XPAR_GPIO_CONTROL_AXI_GPIO_AFE_CONTROL_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_USER_LED_DEVICE_ID,
		XPAR_AXI_GPIO_USER_LED_BASEADDR,
		XPAR_AXI_GPIO_USER_LED_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_USER_LED_IS_DUAL
	}
};


